name: Generate Custom Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate custom snake animation
        uses: Platane/snk@master
        with:
          github_user_name: GeorgeSan97
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
        env:
          SNAKE_COLOR: "#ff7a18"
          BG_COLOR: "transparent"
          DOT_COLOR_0: "#161b22"
          DOT_COLOR_1: "#0e4429"
          DOT_COLOR_2: "#006d32"
          DOT_COLOR_3: "#26a641"
          DOT_COLOR_4: "#39d353"
          GIF_DELAY: "8"

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
