# GitHub Action: Generate Snake Contribution Graph

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake (svg + gif)
        uses: Platane/snk@v3
        with:
          github_user_name: GeorgeSan97

          # üêç Mejora visual y duraci√≥n
          snake_size: 12
          gif_speed: 0.6

          outputs: |
            dist/github-contribution-grid-snake.svg
            ?color_snake=%23ff7a18
            &color_dots=%23161b22,%230e4429,%23006d32,%2326a641,%2339d353

            dist/github-contribution-grid-snake.gif
            ?color_snake=%23ff7a18
            &color_dots=%23161b22,%230e4429,%23006d32,%2326a641,%2339d353
            &color_background=transparent

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

