name: Generate Snake Animation

on:
  schedule: # Ejecuta automáticamente cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar la animación de contribuciones
        uses: Platane/snk@v3
        with:
          github_user_name: GeorgeSan97
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Subir archivo generado
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
